name: Github Profile Update

on:
  schedule: # execute every 24 hours
    - cron: "* */24 * * *"
  workflow_dispatch:

  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-summary-cards
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4

      # For generating github profile summary cards
      - name: generate-github-profile-summary-cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env: # default use ${{ secrets.SUMMARY_GITHUB_TOKEN }}, you should replace with your personal access token
          GITHUB_TOKEN: ${{ secrets.SUMMARY_CARDS_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
          # BRANCH_NAME is optional, default to main, branch name to push cards
          BRANCH_NAME: "main"
          # UTC_OFFSET is optional, default to zero
          UTC_OFFSET: 8

      # For generating snake
      - name: generate github-snake-contribution.svg
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          output: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
      - name: push github-snake-contribution.svg
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env: 
          GITHUB_TOKEN: ${{ secrets.SUMMARY_CARDS_TOKEN }}

